name: mtool release binaries

on:
  release:
  types: [created]

jobs:
  release-matrix:
  name: Release binaries
  runs-on: ubuntu-latest
  strategy:
    matrix:
      goos: [linux darwin windows]
      goarch: [amd64 arm arm64]
  steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: go test ./...
    - uses: wangyoucao577/go-release-action@v1.16
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/mtool"
        binary_name: "mtool"
        extra_files: LICENSE README.md
