on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Binaries for amd64 and arm64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux,windows,darwin]
        goarch: [amd64,arm,arm64]
        exclude:
          - goos: windows
            goarch: arm
          - goos: darwin
            goarch: arm
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: go test ./...
    - uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.20.linux-amd64.tar.gz"
        project_path: "./cmd/mtool"
        binary_name: "mtool"
        extra_files: LICENSE README.md

